# Do not edit this file, please dispatch GHA workflow `update-bootswatch.yaml`

__all__ = ("versions", "themes", )

versions = {
    "5": "5.2.3"
}

themes = {
    "5": [
        "journal",
        "solar",
        "united",
        "vapor",
        "sketchy",
        "morph",
        "minty",
        "litera",
        "cerulean",
        "sandstone",
        "pulse",
        "slate",
        "materia",
        "simplex",
        "lumen",
        "flatly",
        "quartz",
        "cosmo",
        "superhero",
        "cyborg",
        "darkly",
        "lux",
        "zephyr",
        "spacelab",
        "yeti"
    ]
}
